version: 2

jobs:
  test:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
